### ISSUE TITLE
Add gyroscope (HIGH priority)

### ISSUE THREAD

**Issue by gavcradd** [FRUK-Simulator/Simulator#167]
Add a gyroscope to the robot so that it can turn precisely. Requires an output on the sensor screen to show this and a block to read this (to use in loops)

**Comment by MatthiasKreileder** [comment]
The gyroscope has been released by now and a demo program has been provided: https://github.com/FRUK-Simulator/Documentation/blob/master/users/user_guide.md#demo-program-gyroscope-sensor

please let me know of any issues
