### ISSUE TITLE
Lesson 2 challenge completion message is missing on completion

### ISSUE THREAD

**Issue by JamesWP** [FRUK-Simulator/Simulator#189]
need to reproduce this, it might just be some missing code in the lesson event handler

**Comment by ido-ran** [comment]
It seems the problem is the `setTimeout` callback is using a different `this` point so it cannot access the `actions` property of the instance.

https://github.com/FRUK-Simulator/Simulator/blob/938de0f462acdcac11e3dfa327912ed536d6b34f/src/RobotSimulator/Arenas/lesson2.ts#L205-L229

**Comment by ido-ran** [comment]
PR #197 is the simplest fix for this issue but I think we should not use `clearTimeout` but instead keep some running counter which is updated whenever we go in or out of the zone.

**Comment by ido-ran** [comment]
@JamesWP this should be closed as it was fixed. Thanks.
