### ISSUE TITLE
enhance blockly integration with more blocks needed for simple robot control

### ISSUE THREAD

**Issue by JamesWP** [FRUK-Simulator/Simulator#19]
A simple subset of blocks should be added to mirror FTC blockly code editor, hopefully after this is complete we can integrate this with a javascript vm

**Comment by JamesWP** [comment]
Start with: 
- a motor block and simple sensor block.  
- We can create other issues for the other blocks.

**Comment by Casper-Oakley** [comment]
We will also need some additional expressions/control blocks for general purpose programming. Specifically, we'll need booleans, variables, additional iteration and pausing/waiting

**Comment by JamesWP** [comment]
im going to close this issue in favor of more specific items for blocks
