### ISSUE TITLE
Lesson 4 B, C 

### ISSUE THREAD

**Issue by JamesWP** [FRUK-Simulator/Simulator#193]
Black portions are no-go zones, touching them ends the challenge.

Challenge B - includes walls, contact should also end the challenge
![image](https://user-images.githubusercontent.com/707236/137945622-db53b748-fc26-4be5-90f0-c8770875c188.png)

Challenge C
![image](https://user-images.githubusercontent.com/707236/137945490-262b9367-8b68-4ab4-8e99-e7afe1114dfe.png)

**Comment by ido-ran** [comment]
Challange B will be mostly about distance sensor, maybe the course should be a bit more similar to A with walls?

**Comment by JamesWP** [comment]
Challenge B will now be modified to not contain the walls shows in the image and instead require the use of the color sensor to detect the green areas and turn 90 degrees. in addition to this we should consider disabling the use of the distance sensor in this lesson completely (maybe a popup if they use it) also consider adding a coloured  block for the end zone which they must also detect.
