### ISSUE TITLE
Change navigation to stay static

### ISSUE THREAD

**Issue by muktarfirstuk** [FRUK-Simulator/Simulator#207]
Based on user feedback, please can the bar which has "Code, My Programs, Robot, Settings, Challenge" stay static.

**Comment by anap1003** [comment]
Hey @muktarfirstuk do you want the bar to stay in the same place or do you want it moved? Currently, the bar obscures part of the page with text on it.

![image](https://user-images.githubusercontent.com/17729575/153176777-6c8ca3ae-7c54-4498-b743-5ce646f42ef1.png)

We could move it slightly to the right, or move it to be a sidebar perhaps?

**Comment by muktarfirstuk** [comment]
@anap1003 Can we align in to the right so it lives directly within the camera view. Thanks
