### ISSUE TITLE
Reset button for the Simulator

### ISSUE THREAD

**Issue by ginonott** [FRUK-Simulator/Simulator#59]
Since the robot keeps going after a program finished, it would be nice to have a reset button to reset all inputs and outputs.

**Comment by zhiquanyeo** [comment]
Would we want to reset the entire simulation (reset all object positions, etc) or just stop the robot?

**Comment by JamesWP** [comment]
This might nessesitate direct access (not via redux) from various components to the simulator. This will also be needed for sensor data requests.
@ginonott  suggested looking into React providers which allow context to be passed through the element heirachy without needing to be present at every level.

**Comment by JamesWP** [comment]
this has now been completed
