### ISSUE TITLE
create blockly interface to query onscreen controller

### ISSUE THREAD

**Issue by JamesWP** [FRUK-Simulator/Simulator#77]
there should be blocks to query the current state of the controller.

currently, when clicking buttons on the onscreen controller interface motor control events are sent directly to the Sim3D robot handle. alongside this mode of operation there should be another mode where the controller's state is instead visible from the VM. there would also be blocks to access the state of each button on the controller.

**Comment by JamesWP** [comment]
we should try to understand the existing First Tech challenge blocks which do this.

**Comment by Casper-Oakley** [comment]
FTC block for reference (XML can be found in ftc blockly implementation):

![image](https://user-images.githubusercontent.com/5890326/86901148-1dab0a80-c104-11ea-934c-671f8c849218.png)
