### ISSUE TITLE
Add limitation for number of Blockly blocks

### ISSUE THREAD

**Issue by stevenvaneyck** [FRUK-Simulator/Simulator#92]
Some challenges require this. For now just on Blockly side.

Later we can think of integration with arena/challenge selection

**Comment by MatthiasKreileder** [comment]
For anyone who's interested in picking this up:

* It seems Blockly natively supports this, via its `maxBlocks` "Injection Options": https://developers.google.com/blockly/guides/configure/web/configuration_struct 
* Corresponding demo program https://github.com/google/blockly/blob/master/demos/maxBlocks/index.html
